[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fripper"
version = "0.1"
dependencies = [
]

[project.scripts]
fripper = "fripper.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]

