[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "frame_analysis"
version = "0.1"
dependencies = []

[project.scripts]
run_frames = "frame_splitter.__main__:main"

# [tool.setuptools.packages.find]
# where = ["src"]

